VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.pty = true
  config.vm.define "challenge" do |challenge|
    challenge.vm.box = "mcloide/centos-6.5-lamp"
    challenge.vm.network "forwarded_port", guest: 80, host: 8080
    challenge.vm.network "forwarded_port", guest: 443, host: 8443
    challenge.vm.provision "file", source: "wattime.sh", destination: "/tmp/wattime.sh"
    challenge.vm.provision "file", source: "crontab", destination: "/tmp/cronroot"
    challenge.vm.provision "shell", inline: "sudo yum install -y dos2unix ; dos2unix /tmp/wattime.sh ; dos2unix /tmp/cronroot"
    challenge.vm.provision "shell", inline: "mkdir /tmp/wattime ; chmod 777 /tmp/wattime"

    challenge.vm.provision "shell", inline: "sudo install -m 755 -o root -g root /tmp/wattime.sh /usr/bin"
    challenge.vm.provision "shell", inline: "sudo crontab -u root /tmp/cronroot; sudo /etc/init.d/crond restart"
  end
end
